### ISSUE TITLE
Issue with CMS API

### ISSUE THREAD

**Issue by rakaar** [iit-technology-ambit/Apsara2.0#37]
As per the medium article, `URL/jsonapi` on a get request should give data as shown in the pic below
![Screenshot from 2020-03-01 06-54-12](https://user-images.githubusercontent.com/44907757/75617784-d3c87b80-5b89-11ea-9978-328d45e13ffd.png)
But on trying with `https://cms.iit-techambit.in/jsonapi` , we get this
![Screenshot from 2020-03-01 06-56-02](https://user-images.githubusercontent.com/44907757/75617790-ed69c300-5b89-11ea-8597-893e3689267b.png)
Not only that I tried sending get request with axios and fetch API as found in the net, those too failed.
- Is it a bug in CMS API
or 
- Should I change any ways of sending my request

**Comment by thealphadollar** [comment]
Hey,

@rakaar @rashil2000 The issue has been fixed. You need to add the header `Accept: application/vnd.api+json` to all requests.

As seen below, the API is working correctly now. Please embed various endpoints.

Also, the url is `https://cms.iit-techambit.in/api`.

Kindle acknoledge and close the issue.

**Comment by rakaar** [comment]
this works fine !
lets close it
