### ISSUE TITLE
Pagination to show only 9 cards per page

### ISSUE THREAD

**Issue by rakaar** [iit-technology-ambit/Apsara2.0#38]
Also keep pagination to show 9 stories per page

**Comment by rakaar** [comment]
@rashil2000  we shall do this once the number of articles cross 9

**Comment by rashil2000** [comment]
@rakaar The number is 21 now

**Comment by rakaar** [comment]
Okay
Let's start working on it then

**Comment by rakaar** [comment]
Page is fast no need of pagination
