### ISSUE TITLE
Change the fonts in reading page 

### ISSUE THREAD

**Issue by rakaar** [iit-technology-ambit/Apsara2.0#44]
Title font- Vidaloka
Text font- Minion pro

**Comment by rashil2000** [comment]
I've pushed a branch, but I'm unable to preview the font changes

**Comment by thealphadollar** [comment]
Where did you push?

**Comment by rashil2000** [comment]
On a different branch `readingpagefontfix`, to keep things separate.

**Comment by thealphadollar** [comment]
Why are you unable to preview? Any reason? Try to debug.

**Comment by rashil2000** [comment]
I've tried changing port, refreshing, clearing cookies and then refreshing, but to no effect. Other properties (font size, alignment) change, but font doesn't.

**Comment by thealphadollar** [comment]
Try to change it using the chrome developer tools and thereafter make the changes.

**Comment by thealphadollar** [comment]
I just tested it, you need to use "!important" with the styles.

**Comment by rashil2000** [comment]
What's the reason for that?

**Comment by thealphadollar** [comment]
Styling hierarchy.

**Comment by rashil2000** [comment]
We're not using inline fonts. Next in the hierarchy comes the attached css file. I don't understand what has more priority than that.
I also tried putting inline style in the html itself. Isn't that at the top of the hierarchy?

**Comment by thealphadollar** [comment]
Use `!important` for now

**Comment by rashil2000** [comment]
The `!important` is not working for article content. It works only for article title.

**Comment by thealphadollar** [comment]
Figure out for that using debugger. There is always a way
